server {
    listen 80;
    server_name 165.22.210.93;  # Remplacez par votre adresse IP.

    root ;  # Indiquez le chemin vers votre application.
    index index.php;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass unix:/var/run/php/php7.4-fpm.sock;  # Vérifiez le chemin du socket PHP-FPM.
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }
}
